name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '10 2 * * *'
  workflow_dispatch: ~

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
          - current
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test
      - run: npm run eslint
        if: ${{ matrix.node-version == '22' && matrix.os == 'ubuntu-latest' }}
      - name: Coveralls
        if: ${{ matrix.node-version == '22' && matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish codeclimate code coverage
        if: ${{ matrix.node-version == '22' && matrix.os == 'ubuntu-latest' }}
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: d9841018a6538b102775167be6694d17433a951f694e310fa8807f26fe9e0154
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
